// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductApi_DAL;

#nullable disable

namespace ProductApi_DAL.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProductApi.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            id = 2,
                            description = "Sweet and savory sauces relishes spreads and seasonings",
                            name = "Condiments"
                        },
                        new
                        {
                            id = 1,
                            description = "Soft drinks coffees teas beers and ales",
                            name = "Beverages"
                        },
                        new
                        {
                            id = 3,
                            description = "Desserts candies and sweet breads",
                            name = "Confections"
                        },
                        new
                        {
                            id = 4,
                            description = "Cheeses",
                            name = "Dairy Products"
                        },
                        new
                        {
                            id = 5,
                            description = "Breads crackers pasta and cereal",
                            name = "Grains/Cereals"
                        },
                        new
                        {
                            id = 6,
                            description = "Prepared meats",
                            name = "Meat/Poultry"
                        },
                        new
                        {
                            id = 7,
                            description = "Dried fruit and bean curd",
                            name = "Produce"
                        },
                        new
                        {
                            id = 8,
                            description = "Seaweed and fish",
                            name = "Seafood"
                        });
                });

            modelBuilder.Entity("ProductApi.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("categoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool>("discontinued")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantityPerUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("reorderLevel")
                        .HasColumnType("int");

                    b.Property<int>("supplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("unitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("unitsInStock")
                        .HasColumnType("int");

                    b.Property<int>("unitsOnOrder")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("categoryId");

                    b.HasIndex("supplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = 4,
                            categoryId = 3,
                            discontinued = true,
                            name = "Chef Anton's Cajun Seasoning",
                            quantityPerUnit = "48 - 6 oz jars",
                            reorderLevel = 0,
                            supplierId = 2,
                            unitPrice = 22m,
                            unitsInStock = 53,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 5,
                            categoryId = 2,
                            discontinued = true,
                            name = "Chef Anton's Gumbo Mix",
                            quantityPerUnit = "36 boxes",
                            reorderLevel = 0,
                            supplierId = 2,
                            unitPrice = 21.35m,
                            unitsInStock = 0,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 6,
                            categoryId = 2,
                            discontinued = false,
                            name = "Grandma's Boysenberry Spread",
                            quantityPerUnit = "12 - 8 oz jars",
                            reorderLevel = 25,
                            supplierId = 3,
                            unitPrice = 25m,
                            unitsInStock = 120,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 7,
                            categoryId = 7,
                            discontinued = false,
                            name = "Uncle Bob's Organic Dried Pears",
                            quantityPerUnit = "12 - 1 lb pkgs.",
                            reorderLevel = 10,
                            supplierId = 3,
                            unitPrice = 30m,
                            unitsInStock = 15,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 8,
                            categoryId = 2,
                            discontinued = false,
                            name = "Northwoods Cranberry Sauce",
                            quantityPerUnit = "12 - 12 oz jars",
                            reorderLevel = 0,
                            supplierId = 3,
                            unitPrice = 40m,
                            unitsInStock = 6,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 9,
                            categoryId = 6,
                            discontinued = true,
                            name = "Mishi Kobe Niku",
                            quantityPerUnit = "18 - 500 g pkgs.",
                            reorderLevel = 0,
                            supplierId = 4,
                            unitPrice = 97m,
                            unitsInStock = 29,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 10,
                            categoryId = 8,
                            discontinued = false,
                            name = "Ikura",
                            quantityPerUnit = "12 - 200 ml jars",
                            reorderLevel = 0,
                            supplierId = 4,
                            unitPrice = 31m,
                            unitsInStock = 31,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 2,
                            categoryId = 1,
                            discontinued = false,
                            name = "Chang",
                            quantityPerUnit = "24 - 12 oz bottles",
                            reorderLevel = 25,
                            supplierId = 1,
                            unitPrice = 19m,
                            unitsInStock = 17,
                            unitsOnOrder = 40
                        },
                        new
                        {
                            id = 3,
                            categoryId = 2,
                            discontinued = false,
                            name = "Aniseed Syrup",
                            quantityPerUnit = "12 - 550 ml bottles",
                            reorderLevel = 25,
                            supplierId = 1,
                            unitPrice = 10m,
                            unitsInStock = 13,
                            unitsOnOrder = 70
                        },
                        new
                        {
                            id = 11,
                            categoryId = 2,
                            discontinued = false,
                            name = "Queso Cabrales 2",
                            quantityPerUnit = "1 kg pkg.",
                            reorderLevel = 30,
                            supplierId = 5,
                            unitPrice = 21m,
                            unitsInStock = 22,
                            unitsOnOrder = 30
                        },
                        new
                        {
                            id = 12,
                            categoryId = 4,
                            discontinued = false,
                            name = "Queso Manchego La Pastora",
                            quantityPerUnit = "10 - 500 g pkgs.",
                            reorderLevel = 0,
                            supplierId = 5,
                            unitPrice = 38m,
                            unitsInStock = 86,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 13,
                            categoryId = 8,
                            discontinued = false,
                            name = "Konbu",
                            quantityPerUnit = "2 kg box",
                            reorderLevel = 5,
                            supplierId = 6,
                            unitPrice = 6m,
                            unitsInStock = 24,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 14,
                            categoryId = 7,
                            discontinued = false,
                            name = "Tofu",
                            quantityPerUnit = "40 - 100 g pkgs.",
                            reorderLevel = 0,
                            supplierId = 6,
                            unitPrice = 23.25m,
                            unitsInStock = 35,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 15,
                            categoryId = 2,
                            discontinued = false,
                            name = "Genen Shouyu",
                            quantityPerUnit = "24 - 250 ml bottles",
                            reorderLevel = 5,
                            supplierId = 6,
                            unitPrice = 15.5m,
                            unitsInStock = 39,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 1,
                            categoryId = 1,
                            discontinued = false,
                            name = "Chai",
                            quantityPerUnit = "10 boxes x 20 bags",
                            reorderLevel = 10,
                            supplierId = 1,
                            unitPrice = 18m,
                            unitsInStock = 39,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 16,
                            categoryId = 3,
                            discontinued = false,
                            name = "Pavlova",
                            quantityPerUnit = "32 - 500 g boxes",
                            reorderLevel = 10,
                            supplierId = 7,
                            unitPrice = 17.45m,
                            unitsInStock = 29,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 17,
                            categoryId = 6,
                            discontinued = true,
                            name = "Alice Mutton",
                            quantityPerUnit = "20 - 1 kg tins",
                            reorderLevel = 0,
                            supplierId = 7,
                            unitPrice = 39m,
                            unitsInStock = 0,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 18,
                            categoryId = 8,
                            discontinued = false,
                            name = "Carnarvon Tigers",
                            quantityPerUnit = "16 kg pkg.",
                            reorderLevel = 0,
                            supplierId = 7,
                            unitPrice = 62.5m,
                            unitsInStock = 42,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 19,
                            categoryId = 3,
                            discontinued = false,
                            name = "Teatime Chocolate Biscuits",
                            quantityPerUnit = "10 boxes x 12 pieces",
                            reorderLevel = 5,
                            supplierId = 8,
                            unitPrice = 9.2m,
                            unitsInStock = 25,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 20,
                            categoryId = 3,
                            discontinued = false,
                            name = "Sir Rodney's Marmalade",
                            quantityPerUnit = "30 gift boxes",
                            reorderLevel = 0,
                            supplierId = 8,
                            unitPrice = 81m,
                            unitsInStock = 40,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 24,
                            categoryId = 1,
                            discontinued = true,
                            name = "Guaraná Fantástica",
                            quantityPerUnit = "12 - 355 ml cans",
                            reorderLevel = 0,
                            supplierId = 10,
                            unitPrice = 4.5m,
                            unitsInStock = 20,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 25,
                            categoryId = 3,
                            discontinued = false,
                            name = "NuNuCa Nuß-Nougat-Creme",
                            quantityPerUnit = "20 - 450 g glasses",
                            reorderLevel = 30,
                            supplierId = 11,
                            unitPrice = 14m,
                            unitsInStock = 76,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 26,
                            categoryId = 3,
                            discontinued = false,
                            name = "Gumbär Gummibärchen",
                            quantityPerUnit = "100 - 250 g bags",
                            reorderLevel = 0,
                            supplierId = 11,
                            unitPrice = 31.23m,
                            unitsInStock = 15,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 27,
                            categoryId = 3,
                            discontinued = false,
                            name = "Schoggi Schokolade",
                            quantityPerUnit = "100 - 100 g pieces",
                            reorderLevel = 30,
                            supplierId = 11,
                            unitPrice = 43.9m,
                            unitsInStock = 49,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 28,
                            categoryId = 7,
                            discontinued = true,
                            name = "Rössle Sauerkraut",
                            quantityPerUnit = "25 - 825 g cans",
                            reorderLevel = 0,
                            supplierId = 12,
                            unitPrice = 45.6m,
                            unitsInStock = 26,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 29,
                            categoryId = 6,
                            discontinued = true,
                            name = "Thüringer Rostbratwurst",
                            quantityPerUnit = "50 bags x 30 sausgs.",
                            reorderLevel = 0,
                            supplierId = 12,
                            unitPrice = 123.79m,
                            unitsInStock = 0,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 30,
                            categoryId = 8,
                            discontinued = false,
                            name = "Nord-Ost Matjeshering",
                            quantityPerUnit = "10 - 200 g glasses",
                            reorderLevel = 15,
                            supplierId = 13,
                            unitPrice = 25.89m,
                            unitsInStock = 10,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 31,
                            categoryId = 4,
                            discontinued = false,
                            name = "Gorgonzola Telino",
                            quantityPerUnit = "12 - 100 g pkgs",
                            reorderLevel = 20,
                            supplierId = 14,
                            unitPrice = 12.5m,
                            unitsInStock = 0,
                            unitsOnOrder = 70
                        },
                        new
                        {
                            id = 32,
                            categoryId = 4,
                            discontinued = false,
                            name = "Mascarpone Fabioli",
                            quantityPerUnit = "24 - 200 g pkgs.",
                            reorderLevel = 25,
                            supplierId = 14,
                            unitPrice = 32m,
                            unitsInStock = 9,
                            unitsOnOrder = 40
                        },
                        new
                        {
                            id = 33,
                            categoryId = 4,
                            discontinued = false,
                            name = "Geitost",
                            quantityPerUnit = "500 g",
                            reorderLevel = 20,
                            supplierId = 15,
                            unitPrice = 2.5m,
                            unitsInStock = 112,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 34,
                            categoryId = 1,
                            discontinued = false,
                            name = "Sasquatch Ale",
                            quantityPerUnit = "24 - 12 oz bottles",
                            reorderLevel = 15,
                            supplierId = 16,
                            unitPrice = 14m,
                            unitsInStock = 111,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 22,
                            categoryId = 5,
                            discontinued = false,
                            name = "Gustaf's Knäckebröd",
                            quantityPerUnit = "24 - 500 g pkgs.",
                            reorderLevel = 25,
                            supplierId = 9,
                            unitPrice = 21m,
                            unitsInStock = 104,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 21,
                            categoryId = 3,
                            discontinued = false,
                            name = "Sir Rodney's Scones",
                            quantityPerUnit = "24 pkgs. x 4 pieces",
                            reorderLevel = 5,
                            supplierId = 8,
                            unitPrice = 10m,
                            unitsInStock = 3,
                            unitsOnOrder = 40
                        },
                        new
                        {
                            id = 35,
                            categoryId = 1,
                            discontinued = false,
                            name = "Steeleye Stout",
                            quantityPerUnit = "24 - 12 oz bottles",
                            reorderLevel = 15,
                            supplierId = 16,
                            unitPrice = 18m,
                            unitsInStock = 20,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 23,
                            categoryId = 5,
                            discontinued = false,
                            name = "Tunnbröd",
                            quantityPerUnit = "12 - 250 g pkgs.",
                            reorderLevel = 25,
                            supplierId = 9,
                            unitPrice = 9m,
                            unitsInStock = 61,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 37,
                            categoryId = 8,
                            discontinued = false,
                            name = "Gravad lax",
                            quantityPerUnit = "12 - 500 g pkgs.",
                            reorderLevel = 25,
                            supplierId = 17,
                            unitPrice = 26m,
                            unitsInStock = 11,
                            unitsOnOrder = 50
                        },
                        new
                        {
                            id = 40,
                            categoryId = 8,
                            discontinued = false,
                            name = "Boston Crab Meat",
                            quantityPerUnit = "24 - 4 oz tins",
                            reorderLevel = 30,
                            supplierId = 19,
                            unitPrice = 18.4m,
                            unitsInStock = 123,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 38,
                            categoryId = 1,
                            discontinued = false,
                            name = "Côte de Blaye",
                            quantityPerUnit = "12 - 75 cl bottles",
                            reorderLevel = 15,
                            supplierId = 18,
                            unitPrice = 263.5m,
                            unitsInStock = 17,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 36,
                            categoryId = 8,
                            discontinued = false,
                            name = "Inlagd Sill",
                            quantityPerUnit = "24 - 250 g  jars",
                            reorderLevel = 20,
                            supplierId = 17,
                            unitPrice = 19m,
                            unitsInStock = 112,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 41,
                            categoryId = 8,
                            discontinued = false,
                            name = "Jack's New England Clam Chowder",
                            quantityPerUnit = "12 - 12 oz cans",
                            reorderLevel = 10,
                            supplierId = 19,
                            unitPrice = 9.65m,
                            unitsInStock = 85,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 43,
                            categoryId = 1,
                            discontinued = false,
                            name = "Ipoh Coffee",
                            quantityPerUnit = "16 - 500 g tins",
                            reorderLevel = 25,
                            supplierId = 20,
                            unitPrice = 46m,
                            unitsInStock = 17,
                            unitsOnOrder = 10
                        },
                        new
                        {
                            id = 42,
                            categoryId = 5,
                            discontinued = true,
                            name = "Singaporean Hokkien Fried Mee",
                            quantityPerUnit = "32 - 1 kg pkgs.",
                            reorderLevel = 0,
                            supplierId = 20,
                            unitPrice = 14m,
                            unitsInStock = 26,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 46,
                            categoryId = 8,
                            discontinued = false,
                            name = "Spegesild",
                            quantityPerUnit = "4 - 450 g glasses",
                            reorderLevel = 0,
                            supplierId = 21,
                            unitPrice = 12m,
                            unitsInStock = 95,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 47,
                            categoryId = 3,
                            discontinued = false,
                            name = "Zaanse koeken",
                            quantityPerUnit = "10 - 4 oz boxes",
                            reorderLevel = 0,
                            supplierId = 22,
                            unitPrice = 9.5m,
                            unitsInStock = 36,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 48,
                            categoryId = 3,
                            discontinued = false,
                            name = "Chocolade",
                            quantityPerUnit = "10 pkgs.",
                            reorderLevel = 25,
                            supplierId = 22,
                            unitPrice = 12.75m,
                            unitsInStock = 15,
                            unitsOnOrder = 70
                        },
                        new
                        {
                            id = 49,
                            categoryId = 3,
                            discontinued = false,
                            name = "Maxilaku",
                            quantityPerUnit = "24 - 50 g pkgs.",
                            reorderLevel = 15,
                            supplierId = 23,
                            unitPrice = 20m,
                            unitsInStock = 10,
                            unitsOnOrder = 60
                        },
                        new
                        {
                            id = 50,
                            categoryId = 3,
                            discontinued = false,
                            name = "Valkoinen suklaa",
                            quantityPerUnit = "12 - 100 g bars",
                            reorderLevel = 30,
                            supplierId = 23,
                            unitPrice = 16.25m,
                            unitsInStock = 65,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 51,
                            categoryId = 7,
                            discontinued = false,
                            name = "Manjimup Dried Apples",
                            quantityPerUnit = "50 - 300 g pkgs.",
                            reorderLevel = 10,
                            supplierId = 24,
                            unitPrice = 53m,
                            unitsInStock = 20,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 52,
                            categoryId = 5,
                            discontinued = false,
                            name = "Filo Mix",
                            quantityPerUnit = "16 - 2 kg boxes",
                            reorderLevel = 25,
                            supplierId = 24,
                            unitPrice = 7m,
                            unitsInStock = 38,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 53,
                            categoryId = 6,
                            discontinued = true,
                            name = "Perth Pasties",
                            quantityPerUnit = "48 pieces",
                            reorderLevel = 0,
                            supplierId = 24,
                            unitPrice = 32.8m,
                            unitsInStock = 0,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 54,
                            categoryId = 6,
                            discontinued = false,
                            name = "Tourtière",
                            quantityPerUnit = "16 pies",
                            reorderLevel = 10,
                            supplierId = 25,
                            unitPrice = 7.45m,
                            unitsInStock = 21,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 55,
                            categoryId = 6,
                            discontinued = false,
                            name = "Pâté chinois",
                            quantityPerUnit = "24 boxes x 2 pies",
                            reorderLevel = 20,
                            supplierId = 25,
                            unitPrice = 24m,
                            unitsInStock = 115,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 56,
                            categoryId = 5,
                            discontinued = false,
                            name = "Gnocchi di nonna Alice",
                            quantityPerUnit = "24 - 250 g pkgs.",
                            reorderLevel = 30,
                            supplierId = 26,
                            unitPrice = 38m,
                            unitsInStock = 21,
                            unitsOnOrder = 10
                        },
                        new
                        {
                            id = 57,
                            categoryId = 5,
                            discontinued = false,
                            name = "Ravioli Angelo",
                            quantityPerUnit = "24 - 250 g pkgs.",
                            reorderLevel = 20,
                            supplierId = 26,
                            unitPrice = 19.5m,
                            unitsInStock = 36,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 44,
                            categoryId = 2,
                            discontinued = false,
                            name = "Gula Malacca",
                            quantityPerUnit = "20 - 2 kg bags",
                            reorderLevel = 15,
                            supplierId = 20,
                            unitPrice = 19.45m,
                            unitsInStock = 27,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 39,
                            categoryId = 1,
                            discontinued = false,
                            name = "Chartreuse verte",
                            quantityPerUnit = "750 cc per bottle",
                            reorderLevel = 5,
                            supplierId = 18,
                            unitPrice = 18m,
                            unitsInStock = 69,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 59,
                            categoryId = 4,
                            discontinued = false,
                            name = "Raclette Courdavault",
                            quantityPerUnit = "5 kg pkg.",
                            reorderLevel = 0,
                            supplierId = 28,
                            unitPrice = 55m,
                            unitsInStock = 79,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 60,
                            categoryId = 4,
                            discontinued = false,
                            name = "Camembert Pierrot",
                            quantityPerUnit = "15 - 300 g rounds",
                            reorderLevel = 0,
                            supplierId = 28,
                            unitPrice = 34m,
                            unitsInStock = 19,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 45,
                            categoryId = 8,
                            discontinued = false,
                            name = "Rogede sild",
                            quantityPerUnit = "1k pkg.",
                            reorderLevel = 15,
                            supplierId = 21,
                            unitPrice = 9.5m,
                            unitsInStock = 5,
                            unitsOnOrder = 70
                        },
                        new
                        {
                            id = 58,
                            categoryId = 8,
                            discontinued = false,
                            name = "Escargots de Bourgogne",
                            quantityPerUnit = "24 pieces",
                            reorderLevel = 20,
                            supplierId = 27,
                            unitPrice = 13.25m,
                            unitsInStock = 62,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 61,
                            categoryId = 2,
                            discontinued = false,
                            name = "Sirop d'érable",
                            quantityPerUnit = "24 - 500 ml bottles",
                            reorderLevel = 25,
                            supplierId = 29,
                            unitPrice = 28.5m,
                            unitsInStock = 113,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 62,
                            categoryId = 3,
                            discontinued = false,
                            name = "Tarte au sucre",
                            quantityPerUnit = "48 pies",
                            reorderLevel = 0,
                            supplierId = 29,
                            unitPrice = 49.3m,
                            unitsInStock = 17,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 63,
                            categoryId = 2,
                            discontinued = false,
                            name = "Vegie-spread",
                            quantityPerUnit = "15 - 625 g jars",
                            reorderLevel = 5,
                            supplierId = 7,
                            unitPrice = 43.9m,
                            unitsInStock = 24,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 64,
                            categoryId = 5,
                            discontinued = false,
                            name = "Wimmers gute Semmelknödel",
                            quantityPerUnit = "20 bags x 4 pieces",
                            reorderLevel = 30,
                            supplierId = 12,
                            unitPrice = 33.25m,
                            unitsInStock = 22,
                            unitsOnOrder = 80
                        },
                        new
                        {
                            id = 65,
                            categoryId = 2,
                            discontinued = false,
                            name = "Louisiana Fiery Hot Pepper Sauce",
                            quantityPerUnit = "32 - 8 oz bottles",
                            reorderLevel = 0,
                            supplierId = 2,
                            unitPrice = 21.05m,
                            unitsInStock = 76,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 66,
                            categoryId = 2,
                            discontinued = false,
                            name = "Louisiana Hot Spiced Okra",
                            quantityPerUnit = "24 - 8 oz jars",
                            reorderLevel = 20,
                            supplierId = 2,
                            unitPrice = 17m,
                            unitsInStock = 4,
                            unitsOnOrder = 100
                        },
                        new
                        {
                            id = 67,
                            categoryId = 1,
                            discontinued = false,
                            name = "Laughing Lumberjack Lager",
                            quantityPerUnit = "24 - 12 oz bottles",
                            reorderLevel = 10,
                            supplierId = 16,
                            unitPrice = 14m,
                            unitsInStock = 52,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 68,
                            categoryId = 3,
                            discontinued = false,
                            name = "Scottish Longbreads",
                            quantityPerUnit = "10 boxes x 8 pieces",
                            reorderLevel = 15,
                            supplierId = 8,
                            unitPrice = 12.5m,
                            unitsInStock = 6,
                            unitsOnOrder = 10
                        },
                        new
                        {
                            id = 70,
                            categoryId = 1,
                            discontinued = false,
                            name = "Outback Lager",
                            quantityPerUnit = "24 - 355 ml bottles",
                            reorderLevel = 30,
                            supplierId = 7,
                            unitPrice = 15m,
                            unitsInStock = 15,
                            unitsOnOrder = 10
                        },
                        new
                        {
                            id = 71,
                            categoryId = 4,
                            discontinued = false,
                            name = "Flotemysost",
                            quantityPerUnit = "10 - 500 g pkgs.",
                            reorderLevel = 0,
                            supplierId = 15,
                            unitPrice = 21.5m,
                            unitsInStock = 26,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 73,
                            categoryId = 8,
                            discontinued = false,
                            name = "Röd Kaviar",
                            quantityPerUnit = "24 - 150 g jars",
                            reorderLevel = 5,
                            supplierId = 17,
                            unitPrice = 15m,
                            unitsInStock = 101,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 74,
                            categoryId = 7,
                            discontinued = false,
                            name = "Longlife Tofu",
                            quantityPerUnit = "5 kg pkg.",
                            reorderLevel = 5,
                            supplierId = 4,
                            unitPrice = 10m,
                            unitsInStock = 4,
                            unitsOnOrder = 20
                        },
                        new
                        {
                            id = 75,
                            categoryId = 1,
                            discontinued = false,
                            name = "Rhönbräu Klosterbier",
                            quantityPerUnit = "24 - 0.5 l bottles",
                            reorderLevel = 25,
                            supplierId = 12,
                            unitPrice = 7.75m,
                            unitsInStock = 125,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 76,
                            categoryId = 1,
                            discontinued = false,
                            name = "Lakkalikööri",
                            quantityPerUnit = "500 ml",
                            reorderLevel = 20,
                            supplierId = 23,
                            unitPrice = 18m,
                            unitsInStock = 57,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 69,
                            categoryId = 4,
                            discontinued = false,
                            name = "Gudbrandsdalsost",
                            quantityPerUnit = "10 kg pkg.",
                            reorderLevel = 15,
                            supplierId = 15,
                            unitPrice = 36m,
                            unitsInStock = 26,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 72,
                            categoryId = 4,
                            discontinued = false,
                            name = "Mozzarella di Giovanni",
                            quantityPerUnit = "24 - 200 g pkgs.",
                            reorderLevel = 0,
                            supplierId = 14,
                            unitPrice = 34.8m,
                            unitsInStock = 14,
                            unitsOnOrder = 0
                        },
                        new
                        {
                            id = 77,
                            categoryId = 2,
                            discontinued = false,
                            name = "Original Frankfurter grüne Soße",
                            quantityPerUnit = "12 boxes",
                            reorderLevel = 15,
                            supplierId = 12,
                            unitPrice = 13m,
                            unitsInStock = 32,
                            unitsOnOrder = 0
                        });
                });

            modelBuilder.Entity("ProductApi.Models.Supplier", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            id = 4,
                            companyName = "Tokyo Traders",
                            contactName = "Yoshi Nagase",
                            contactTitle = "Marketing Manager",
                            strAddress = "9-8 Sekimai Musashino-shi Tokyo NULL 100 Japan (03) 3555-5011"
                        },
                        new
                        {
                            id = 5,
                            companyName = "Cooperativa de Quesos 'Las Cabras'",
                            contactName = "Antonio del Valle Saavedra",
                            contactTitle = "Export Administrator",
                            strAddress = "Calle del Rosal 4 Oviedo Asturias 33007 Spain (98) 598 76 54"
                        },
                        new
                        {
                            id = 6,
                            companyName = "Mayumi's",
                            contactName = "Mayumi Ohno",
                            contactTitle = "Marketing Representative",
                            strAddress = "92 Setsuko Chuo-ku Osaka NULL 545 Japan (06) 431-7877"
                        },
                        new
                        {
                            id = 7,
                            companyName = "Pavlova Ltd.",
                            contactName = "Ian Devling",
                            contactTitle = "Marketing Manager",
                            strAddress = "74 Rose St. Moonie Ponds Melbourne Victoria 3058 Australia (03) 444-2343"
                        },
                        new
                        {
                            id = 8,
                            companyName = "Specialty Biscuits Ltd.",
                            contactName = "Peter Wilson",
                            contactTitle = "Sales Representative",
                            strAddress = "29 King's Way Manchester NULL M14 GSD UK (161) 555-4448"
                        },
                        new
                        {
                            id = 9,
                            companyName = "PB Knäckebröd AB",
                            contactName = "Lars Peterson",
                            contactTitle = "Sales Agent",
                            strAddress = "Kaloadagatan 13 Göteborg NULL S-345 67 Sweden 031-987 65 43"
                        },
                        new
                        {
                            id = 10,
                            companyName = "Refrescos Americanas LTDA",
                            contactName = "Carlos Diaz",
                            contactTitle = "Marketing Manager",
                            strAddress = "Av. das Americanas 12.890 Sao Paulo NULL 5442 Brazil (11) 555 4640"
                        },
                        new
                        {
                            id = 11,
                            companyName = "Heli Süßwaren GmbH & Co. KG",
                            contactName = "Petra Winkler",
                            contactTitle = "Sales Manager",
                            strAddress = "Tiergartenstraße 5 Berlin NULL 10785 Germany (010) 9984510"
                        },
                        new
                        {
                            id = 2,
                            companyName = "New Orleans Cajun Delights",
                            contactName = "Shelley Burke",
                            contactTitle = "Order Administrator",
                            strAddress = "P.O. Box 78934 New Orleans LA 70117 USA (100) 555-4822"
                        },
                        new
                        {
                            id = 12,
                            companyName = "Plutzer Lebensmittelgroßmärkte AG",
                            contactName = "Martin Bein",
                            contactTitle = "International Marketing Mgr.",
                            strAddress = "Bogenallee 51 Frankfurt NULL 60439 Germany (069) 992755"
                        },
                        new
                        {
                            id = 13,
                            companyName = "Nord-Ost-Fisch Handelsgesellschaft mbH",
                            contactName = "Sven Petersen",
                            contactTitle = "Coordinator Foreign Markets",
                            strAddress = "Frahmredder 112a Cuxhaven NULL 27478 Germany (04721) 8713"
                        },
                        new
                        {
                            id = 14,
                            companyName = "Formaggi Fortini s.r.l.",
                            contactName = "Elio Rossi",
                            contactTitle = "Sales Representative",
                            strAddress = "Viale Dante 75 Ravenna NULL 48100 Italy (0544) 60323"
                        },
                        new
                        {
                            id = 15,
                            companyName = "Norske Meierier",
                            contactName = "Beate Vileid",
                            contactTitle = "Marketing Manager",
                            strAddress = "Hatlevegen 5 Sandvika NULL 1320 Norway (0)2-953010"
                        },
                        new
                        {
                            id = 1,
                            companyName = "Exotic Liquids",
                            contactName = "Charlotte Cooper",
                            contactTitle = "Purchasing Manager",
                            strAddress = "49 Gilbert St. London NULL EC1 4SD UK (171) 555-2222"
                        },
                        new
                        {
                            id = 3,
                            companyName = "Grandma Kelly's Homestead",
                            contactName = "Regina Murphy",
                            contactTitle = "Sales Representative",
                            strAddress = "707 Oxford Rd. Ann Arbor MI 48104 USA (313) 555-5735"
                        },
                        new
                        {
                            id = 16,
                            companyName = "Bigfoot Breweries",
                            contactName = "Cheryl Saylor",
                            contactTitle = "Regional Account Rep.",
                            strAddress = "3400 - 8th Avenue Suite 210 Bend OR 97101 USA (503) 555-9931"
                        },
                        new
                        {
                            id = 17,
                            companyName = "Svensk Sjöföda AB",
                            contactName = "Michael Björn",
                            contactTitle = "Sales Representative",
                            strAddress = "Brovallavägen 231 Stockholm NULL S-123 45 Sweden 08-123 45 67"
                        },
                        new
                        {
                            id = 18,
                            companyName = "Aux joyeux ecclésiastiques",
                            contactName = "Guylène Nodier",
                            contactTitle = "Sales Manager",
                            strAddress = "203 Rue des Francs-Bourgeois Paris NULL 75004 France (1) 03.83.00.68"
                        },
                        new
                        {
                            id = 19,
                            companyName = "New England Seafood Cannery",
                            contactName = "Robb Merchant",
                            contactTitle = "Wholesale Account Agent",
                            strAddress = "Order Processing Dept. 2100 Paul Revere Blvd. Boston MA 2134 USA (617) 555-3267"
                        },
                        new
                        {
                            id = 20,
                            companyName = "Leka Trading",
                            contactName = "Chandra Leka",
                            contactTitle = "Owner",
                            strAddress = "471 Serangoon Loop Suite #402 Singapore NULL 512 Singapore 555-8787"
                        },
                        new
                        {
                            id = 21,
                            companyName = "Lyngbysild",
                            contactName = "Niels Petersen",
                            contactTitle = "Sales Manager",
                            strAddress = "Lyngbysild Fiskebakken 10 Lyngby NULL 2800 Denmark 43844108"
                        },
                        new
                        {
                            id = 22,
                            companyName = "Zaanse Snoepfabriek",
                            contactName = "Dirk Luchte",
                            contactTitle = "Accounting Manager",
                            strAddress = "Verkoop Rijnweg 22 Zaandam NULL 9999 ZZ Netherlands (12345) 1212"
                        },
                        new
                        {
                            id = 25,
                            companyName = "Ma Maison",
                            contactName = "Jean-Guy Lauzon",
                            contactTitle = "Marketing Manager",
                            strAddress = "2960 Rue St. Laurent Montréal Québec H1J 1C3 Canada (514) 555-9022"
                        },
                        new
                        {
                            id = 27,
                            companyName = "Escargots Nouveaux",
                            contactName = "Marie Delamare",
                            contactTitle = "Sales Manager",
                            strAddress = "22 rue H. Voiron Montceau NULL 71300 France 85.57.00.07"
                        },
                        new
                        {
                            id = 26,
                            companyName = "Pasta Buttini s.r.l.",
                            contactName = "Giovanni Giudici",
                            contactTitle = "Order Administrator",
                            strAddress = "Via dei Gelsomini 153 Salerno NULL 84100 Italy (089) 6547665"
                        },
                        new
                        {
                            id = 28,
                            companyName = "Gai pâturage",
                            contactName = "Eliane Noz",
                            contactTitle = "Sales Representative",
                            strAddress = "Bat. B 3 rue des Alpes Annecy NULL 74000 France 38.76.98.06"
                        },
                        new
                        {
                            id = 23,
                            companyName = "Karkki Oy",
                            contactName = "Anne Heikkonen",
                            contactTitle = "Product Manager",
                            strAddress = "Valtakatu 12 Lappeenranta NULL 53120 Finland (953) 10956"
                        },
                        new
                        {
                            id = 24,
                            companyName = "G'day Mate",
                            contactName = "Wendy Mackenzie",
                            contactTitle = "Sales Representative",
                            strAddress = "170 Prince Edward Parade Hunter's Hill Sydney NSW 2042 Australia (02) 555-5914"
                        },
                        new
                        {
                            id = 29,
                            companyName = "Forêts d'érables",
                            contactName = "Chantal Goulet",
                            contactTitle = "Accounting Manager",
                            strAddress = "148 rue Chasseur Ste-Hyacinthe Québec J2S 7S8 Canada (514) 555-2955"
                        },
                        new
                        {
                            id = 30,
                            companyName = "aaaaaaa",
                            contactName = "a",
                            strAddress = "     a"
                        });
                });

            modelBuilder.Entity("ProductApi.Models.Product", b =>
                {
                    b.HasOne("ProductApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductApi.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("supplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ProductApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProductApi.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
